name: Check PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify Checklist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching Pull Request Information..."
        PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q '.body')
        
        echo "Checking Checklist in PR..."
        MISSING=$(echo "$PR_BODY" | grep -o '\[ \]' | wc -l)

        if [ "$MISSING" -gt 0 ]; then
          echo "Error: $MISSING checklist item(s) are not checked. Please complete the checklist."
          exit 1
        else
          echo "All checklist items are checked."
        fi
